# Generated by Django 2.0.9 on 2018-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
