# Generated by Django 2.0.9 on 2018-11-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('run', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('fechanac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('tipov', models.CharField(max_length=50)),
            ],
        ),
    ]
